# Generated by Django 5.2.7 on 2025-11-13 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0003_alter_book_options'),
    ]

    operations = [
    ]
